package com.chiragus.SimplePaint;

import java.awt.BorderLayout;
import java.awt.GridLayout;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 * The content pane of the UXPaint program
 * 
 * @author Chirag Uttamsingh
 * @version 2017.09 - initial implementation
 * @since 2017.09
 */

public class PaintUXPanel extends JPanel{
	
	/**
	 * Generated by eclipse
	 */
	private static final long serialVersionUID = 8502190913617018509L;

	public PaintUXPanel() {
		setLayout(new BorderLayout());
		
		// main central buffer
		add(new BufferPane(), BorderLayout.CENTER);		
		
		// south buttons
		JPanel buttonPanel = new JPanel();
		JButton saveButton = new JButton("Save");
		saveButton.setIcon(new ImageIcon("src/img/check.png"));
		JButton printButton = new JButton("Print");
		printButton.setIcon(new ImageIcon("src/img/printer3.png"));
		JButton closeButton = new JButton("Close");
		closeButton.setIcon(new ImageIcon("src/img/cross.png"));
		
		buttonPanel.add(saveButton);
		buttonPanel.add(printButton);
		buttonPanel.add(closeButton);
		
		add(buttonPanel, BorderLayout.SOUTH);
		
		// west tools
		JPanel toolsPanel = new JPanel();
		toolsPanel.setLayout(new GridLayout(0, 1));
		
		JButton penButton = new JButton(new ImageIcon("src/img/draft_pen2.png"));
		JButton eraserButton = new JButton(new ImageIcon("src/img/eraser2.png"));
		
		toolsPanel.add(penButton);
		toolsPanel.add(eraserButton);
		
		add(toolsPanel, BorderLayout.WEST);
		
		
	}

}
